"""Fixed layout for EFD-ICMS/IPI reports."""

CABECALHO_ICMS_IPI = [
    "CNPJ",
    "Período",
    "Registros",
    "Tipo Operação",
    "Indicador Emitente",
    "Situação",
    "Código Participante",
    "CNPJ/CPF Participante",
    "Nome Participante",
    "UF Origem/Destino",
    "Regime Tributário",
    "Número Documento",
    "Série",
    "Modelo",
    "Chave NF-e",
    "Data Documento",
    "Data Entrada/Saída",
    "Vlr Documento",
    "Vlr Desconto NF",
    "Vlr Mercadoria",
    "Vlr Frete",
    "Vlr Seguro",
    "Vlr Outras DA",
    "Número Item",
    "Código Item",
    "Descrição Item",
    "Tipo Item",
    "Código Barra",
    "NCM",
    "Vlr Operação",
    "Vlr Item",
    "Vlr Desconto Item",
    "Qtde",
    "Unidade Medida",
    "Indicador Movimento",
    "CFOP",
    "Descrição CFOP",
    "CFOP Faturamento",
    "CST ICMS",
    "Vlr Base Cálculo ICMS",
    "Vlr Redução Base ICMS",
    "Alíquota ICMS",
    "Vlr ICMS",
    "Vlr Base Cálculo ICMS ST",
    "Alíquota ICMS ST",
    "Vlr ICMS ST",
    "CST IPI",
    "Vlr Base Cálculo IPI",
    "Alíquota IPI",
    "Vlr IPI",
    "CST PIS",
    "Vlr Base Cálculo PIS",
    "Alíquota PIS",
    "Vlr PIS",
    "CST Cofins",
    "Vlr Base Cálculo Cofins",
    "Alíquota Cofins",
    "Vlr Cofins",
    "Conta Contábil",
]
