"""Fixed layout for EFD-Contribuicoes reports."""

CABECALHO_CONTRIBUICOES = [
    "CNPJ",
    "Período",
    "Registros",
    "Tipo Operação",
    "Situação",
    "Código Participante",
    "CNPJ Participante",
    "CPF Participante",
    "Nome Participante",
    "Regime Tributário",
    "UF Origem/Destino",
    "Número Documento",
    "Série",
    "Chave NF-e",
    "Data Documento",
    "Data Entrada/Saída",
    "Vlr Documento",
    "Vlr Desconto NF",
    "Vlr Mercadoria/Operação",
    "Vlr Frete",
    "Vlr Seguro",
    "Vlr Outras DA",
    "Número Item",
    "Código Item",
    "Descrição Complementar",
    "Descrição Item",
    "NCM",
    "Código Serviço",
    "Código Barra",
    "Tipo Item",
    "Vlr Item",
    "Qtde",
    "Unidade Medida",
    "Vlr Desconto Item",
    "Natureza Crédito",
    "CFOP",
    "Descrição CFOP",
    "CFOP Faturamento",
    "CST ICMS",
    "Vlr Base Cálculo ICMS",
    "Alíquota ICMS",
    "Vlr ICMS",
    "Vlr Base Cálculo ICMS ST",
    "Alíquota ICMS ST",
    "Vlr ICMS ST",
    "CST IPI",
    "Vlr Base Cálculo IPI",
    "Alíquota IPI",
    "Vlr IPI",
    "CST PIS",
    "Vlr Base Cálculo PIS",
    "Qtde Base Cálculo PIS",
    "Alíquota PIS",
    "Qtde Alíquota PIS",
    "Vlr PIS",
    "CST Cofins",
    "Vlr Base Cálculo Cofins",
    "Qtde Base Cálculo Cofins",
    "Alíquota Cofins",
    "Qtde Alíquota Cofins",
    "Vlr Cofins",
    "Conta Contábil",
    "Débito/Crédito",
]
